// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: layout/v1/layout.proto

package v1

import (
	v1 "github.com/nightmarlin/murum/protos/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bounds *v1.Rect `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`                // How large the image will be.
	XCount int32    `protobuf:"varint,2,opt,name=x_count,json=xCount,proto3" json:"x_count,omitempty"` // How many points to place along the x-axis of the Layout.
	YCount int32    `protobuf:"varint,3,opt,name=y_count,json=yCount,proto3" json:"y_count,omitempty"` // How many points to place along the y-axis of the Layout.
	// Types that are assignable to Mode:
	//
	//	*GenerateRequest_Random
	//	*GenerateRequest_Even
	//	*GenerateRequest_Varied
	//	*GenerateRequest_Triangular
	//	*GenerateRequest_Weighted
	Mode isGenerateRequest_Mode `protobuf_oneof:"mode"`
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetBounds() *v1.Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *GenerateRequest) GetXCount() int32 {
	if x != nil {
		return x.XCount
	}
	return 0
}

func (x *GenerateRequest) GetYCount() int32 {
	if x != nil {
		return x.YCount
	}
	return 0
}

func (m *GenerateRequest) GetMode() isGenerateRequest_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *GenerateRequest) GetRandom() *RandomParams {
	if x, ok := x.GetMode().(*GenerateRequest_Random); ok {
		return x.Random
	}
	return nil
}

func (x *GenerateRequest) GetEven() *EvenParams {
	if x, ok := x.GetMode().(*GenerateRequest_Even); ok {
		return x.Even
	}
	return nil
}

func (x *GenerateRequest) GetVaried() *VariedParams {
	if x, ok := x.GetMode().(*GenerateRequest_Varied); ok {
		return x.Varied
	}
	return nil
}

func (x *GenerateRequest) GetTriangular() *TriangularParams {
	if x, ok := x.GetMode().(*GenerateRequest_Triangular); ok {
		return x.Triangular
	}
	return nil
}

func (x *GenerateRequest) GetWeighted() *WeightedParams {
	if x, ok := x.GetMode().(*GenerateRequest_Weighted); ok {
		return x.Weighted
	}
	return nil
}

type isGenerateRequest_Mode interface {
	isGenerateRequest_Mode()
}

type GenerateRequest_Random struct {
	Random *RandomParams `protobuf:"bytes,4,opt,name=random,proto3,oneof"`
}

type GenerateRequest_Even struct {
	Even *EvenParams `protobuf:"bytes,5,opt,name=even,proto3,oneof"`
}

type GenerateRequest_Varied struct {
	Varied *VariedParams `protobuf:"bytes,6,opt,name=varied,proto3,oneof"`
}

type GenerateRequest_Triangular struct {
	Triangular *TriangularParams `protobuf:"bytes,7,opt,name=triangular,proto3,oneof"`
}

type GenerateRequest_Weighted struct {
	Weighted *WeightedParams `protobuf:"bytes,8,opt,name=weighted,proto3,oneof"`
}

func (*GenerateRequest_Random) isGenerateRequest_Mode() {}

func (*GenerateRequest_Even) isGenerateRequest_Mode() {}

func (*GenerateRequest_Varied) isGenerateRequest_Mode() {}

func (*GenerateRequest_Triangular) isGenerateRequest_Mode() {}

func (*GenerateRequest_Weighted) isGenerateRequest_Mode() {}

// A Random Layout places the specified number of points randomly within the
// Bounds.
type RandomParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RandomParams) Reset() {
	*x = RandomParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomParams) ProtoMessage() {}

func (x *RandomParams) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomParams.ProtoReflect.Descriptor instead.
func (*RandomParams) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{1}
}

// An Even Layout places the specified number of points evenly across the
// Bounds.
type EvenParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvenParams) Reset() {
	*x = EvenParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvenParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvenParams) ProtoMessage() {}

func (x *EvenParams) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvenParams.ProtoReflect.Descriptor instead.
func (*EvenParams) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{2}
}

// A Varied Layout places the points as in Even, but then randomly moves them
// within the bounds defined by the specified offsets.
type VariedParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MinXOffset int32 `protobuf:"varint,1,opt,name=min_x_offset,json=minXOffset,proto3" json:"min_x_offset,omitempty"`
	MinYOffset int32 `protobuf:"varint,2,opt,name=min_y_offset,json=minYOffset,proto3" json:"min_y_offset,omitempty"`
	MaxXOffset int32 `protobuf:"varint,3,opt,name=max_x_offset,json=maxXOffset,proto3" json:"max_x_offset,omitempty"`
	MaxYOffset int32 `protobuf:"varint,4,opt,name=max_y_offset,json=maxYOffset,proto3" json:"max_y_offset,omitempty"`
}

func (x *VariedParams) Reset() {
	*x = VariedParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VariedParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariedParams) ProtoMessage() {}

func (x *VariedParams) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariedParams.ProtoReflect.Descriptor instead.
func (*VariedParams) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{3}
}

func (x *VariedParams) GetMinXOffset() int32 {
	if x != nil {
		return x.MinXOffset
	}
	return 0
}

func (x *VariedParams) GetMinYOffset() int32 {
	if x != nil {
		return x.MinYOffset
	}
	return 0
}

func (x *VariedParams) GetMaxXOffset() int32 {
	if x != nil {
		return x.MaxXOffset
	}
	return 0
}

func (x *VariedParams) GetMaxYOffset() int32 {
	if x != nil {
		return x.MaxYOffset
	}
	return 0
}

// Triangular layouts are in progress.
type TriangularParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TriangularParams) Reset() {
	*x = TriangularParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriangularParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriangularParams) ProtoMessage() {}

func (x *TriangularParams) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriangularParams.ProtoReflect.Descriptor instead.
func (*TriangularParams) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{4}
}

// Weighted layouts are in progress.
type WeightedParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Center  *v1.Point `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Gravity float64   `protobuf:"fixed64,2,opt,name=gravity,proto3" json:"gravity,omitempty"`
}

func (x *WeightedParams) Reset() {
	*x = WeightedParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightedParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightedParams) ProtoMessage() {}

func (x *WeightedParams) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightedParams.ProtoReflect.Descriptor instead.
func (*WeightedParams) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{5}
}

func (x *WeightedParams) GetCenter() *v1.Point {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *WeightedParams) GetGravity() float64 {
	if x != nil {
		return x.Gravity
	}
	return 0
}

type Region struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Center  *v1.Point   `protobuf:"bytes,1,opt,name=center,proto3" json:"center,omitempty"`
	Members []*v1.Point `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
}

func (x *Region) Reset() {
	*x = Region{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{6}
}

func (x *Region) GetCenter() *v1.Point {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *Region) GetMembers() []*v1.Point {
	if x != nil {
		return x.Members
	}
	return nil
}

type Layout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bounds  *v1.Rect  `protobuf:"bytes,1,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Regions []*Region `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
}

func (x *Layout) Reset() {
	*x = Layout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layout) ProtoMessage() {}

func (x *Layout) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layout.ProtoReflect.Descriptor instead.
func (*Layout) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{7}
}

func (x *Layout) GetBounds() *v1.Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *Layout) GetRegions() []*Region {
	if x != nil {
		return x.Regions
	}
	return nil
}

type GenerateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layout *Layout `protobuf:"bytes,1,opt,name=layout,proto3" json:"layout,omitempty"`
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layout_v1_layout_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_layout_v1_layout_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_layout_v1_layout_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateResponse) GetLayout() *Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

var File_layout_v1_layout_proto protoreflect.FileDescriptor

var file_layout_v1_layout_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x1a, 0x16, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xed, 0x02, 0x0a, 0x0f, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e,
	0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x78, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x78, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x79,
	0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x06, 0x72, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x12, 0x28, 0x0a, 0x04, 0x65, 0x76, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x04, 0x65, 0x76, 0x65, 0x6e, 0x12, 0x2e,
	0x0a, 0x06, 0x76, 0x61, 0x72, 0x69, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x65, 0x64, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x06, 0x76, 0x61, 0x72, 0x69, 0x65, 0x64, 0x12, 0x3a,
	0x0a, 0x0a, 0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x54, 0x72, 0x69, 0x61,
	0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x0a,
	0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x12, 0x34, 0x0a, 0x08, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x08, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64,
	0x42, 0x06, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x61, 0x6e, 0x64,
	0x6f, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x76, 0x65, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x0c, 0x56, 0x61, 0x72, 0x69, 0x65,
	0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x5f, 0x78,
	0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d,
	0x69, 0x6e, 0x58, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6d, 0x69, 0x6e,
	0x5f, 0x79, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x6d, 0x69, 0x6e, 0x59, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x6d,
	0x61, 0x78, 0x5f, 0x78, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x58, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a,
	0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x79, 0x5f, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x59, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22,
	0x12, 0x0a, 0x10, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x75, 0x6c, 0x61, 0x72, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x51, 0x0a, 0x0e, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x65, 0x64, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x67, 0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x67,
	0x72, 0x61, 0x76, 0x69, 0x74, 0x79, 0x22, 0x58, 0x0a, 0x06, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x25, 0x0a, 0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x06, 0x63, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x22, 0x58, 0x0a, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x62, 0x6f,
	0x75, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x52, 0x06, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x73,
	0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3a, 0x0a, 0x10, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26,
	0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x06,
	0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x32, 0x4e, 0x0a, 0x0d, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x80, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x6c,
	0x61, 0x79, 0x6f, 0x75, 0x74, 0x42, 0x0b, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6e, 0x69, 0x67, 0x68, 0x74, 0x6d, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x2f, 0x6d, 0x75, 0x72,
	0x75, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x2f, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x4c, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x4c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0xca, 0x02, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0xe2, 0x02, 0x12, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x06, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_layout_v1_layout_proto_rawDescOnce sync.Once
	file_layout_v1_layout_proto_rawDescData = file_layout_v1_layout_proto_rawDesc
)

func file_layout_v1_layout_proto_rawDescGZIP() []byte {
	file_layout_v1_layout_proto_rawDescOnce.Do(func() {
		file_layout_v1_layout_proto_rawDescData = protoimpl.X.CompressGZIP(file_layout_v1_layout_proto_rawDescData)
	})
	return file_layout_v1_layout_proto_rawDescData
}

var file_layout_v1_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_layout_v1_layout_proto_goTypes = []interface{}{
	(*GenerateRequest)(nil),  // 0: layout.GenerateRequest
	(*RandomParams)(nil),     // 1: layout.RandomParams
	(*EvenParams)(nil),       // 2: layout.EvenParams
	(*VariedParams)(nil),     // 3: layout.VariedParams
	(*TriangularParams)(nil), // 4: layout.TriangularParams
	(*WeightedParams)(nil),   // 5: layout.WeightedParams
	(*Region)(nil),           // 6: layout.Region
	(*Layout)(nil),           // 7: layout.Layout
	(*GenerateResponse)(nil), // 8: layout.GenerateResponse
	(*v1.Rect)(nil),          // 9: shared.Rect
	(*v1.Point)(nil),         // 10: shared.Point
}
var file_layout_v1_layout_proto_depIdxs = []int32{
	9,  // 0: layout.GenerateRequest.bounds:type_name -> shared.Rect
	1,  // 1: layout.GenerateRequest.random:type_name -> layout.RandomParams
	2,  // 2: layout.GenerateRequest.even:type_name -> layout.EvenParams
	3,  // 3: layout.GenerateRequest.varied:type_name -> layout.VariedParams
	4,  // 4: layout.GenerateRequest.triangular:type_name -> layout.TriangularParams
	5,  // 5: layout.GenerateRequest.weighted:type_name -> layout.WeightedParams
	10, // 6: layout.WeightedParams.center:type_name -> shared.Point
	10, // 7: layout.Region.center:type_name -> shared.Point
	10, // 8: layout.Region.members:type_name -> shared.Point
	9,  // 9: layout.Layout.bounds:type_name -> shared.Rect
	6,  // 10: layout.Layout.regions:type_name -> layout.Region
	7,  // 11: layout.GenerateResponse.layout:type_name -> layout.Layout
	0,  // 12: layout.LayoutService.Generate:input_type -> layout.GenerateRequest
	8,  // 13: layout.LayoutService.Generate:output_type -> layout.GenerateResponse
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_layout_v1_layout_proto_init() }
func file_layout_v1_layout_proto_init() {
	if File_layout_v1_layout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_layout_v1_layout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvenParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VariedParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriangularParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeightedParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Region); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layout_v1_layout_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_layout_v1_layout_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GenerateRequest_Random)(nil),
		(*GenerateRequest_Even)(nil),
		(*GenerateRequest_Varied)(nil),
		(*GenerateRequest_Triangular)(nil),
		(*GenerateRequest_Weighted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_layout_v1_layout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_layout_v1_layout_proto_goTypes,
		DependencyIndexes: file_layout_v1_layout_proto_depIdxs,
		MessageInfos:      file_layout_v1_layout_proto_msgTypes,
	}.Build()
	File_layout_v1_layout_proto = out.File
	file_layout_v1_layout_proto_rawDesc = nil
	file_layout_v1_layout_proto_goTypes = nil
	file_layout_v1_layout_proto_depIdxs = nil
}
