// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: render/v1/render.proto

package v1

import (
	v11 "github.com/nightmarlin/murum/protos/layout/v1"
	v1 "github.com/nightmarlin/murum/protos/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileType v1.FileType `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3,enum=shared.FileType" json:"file_type,omitempty"`
	Layout   *v11.Layout `protobuf:"bytes,2,opt,name=layout,proto3" json:"layout,omitempty"`
	Images   []*v1.Image `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	// Types that are assignable to Mode:
	//
	//	*RenderRequest_Basic
	//	*RenderRequest_WithText
	Mode isRenderRequest_Mode `protobuf_oneof:"mode"`
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_render_v1_render_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_render_v1_render_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_render_v1_render_proto_rawDescGZIP(), []int{0}
}

func (x *RenderRequest) GetFileType() v1.FileType {
	if x != nil {
		return x.FileType
	}
	return v1.FileType(0)
}

func (x *RenderRequest) GetLayout() *v11.Layout {
	if x != nil {
		return x.Layout
	}
	return nil
}

func (x *RenderRequest) GetImages() []*v1.Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (m *RenderRequest) GetMode() isRenderRequest_Mode {
	if m != nil {
		return m.Mode
	}
	return nil
}

func (x *RenderRequest) GetBasic() *BasicParams {
	if x, ok := x.GetMode().(*RenderRequest_Basic); ok {
		return x.Basic
	}
	return nil
}

func (x *RenderRequest) GetWithText() *WithTextParams {
	if x, ok := x.GetMode().(*RenderRequest_WithText); ok {
		return x.WithText
	}
	return nil
}

type isRenderRequest_Mode interface {
	isRenderRequest_Mode()
}

type RenderRequest_Basic struct {
	Basic *BasicParams `protobuf:"bytes,4,opt,name=basic,proto3,oneof"`
}

type RenderRequest_WithText struct {
	WithText *WithTextParams `protobuf:"bytes,5,opt,name=with_text,json=withText,proto3,oneof"`
}

func (*RenderRequest_Basic) isRenderRequest_Mode() {}

func (*RenderRequest_WithText) isRenderRequest_Mode() {}

type BasicParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BasicParams) Reset() {
	*x = BasicParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_render_v1_render_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicParams) ProtoMessage() {}

func (x *BasicParams) ProtoReflect() protoreflect.Message {
	mi := &file_render_v1_render_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicParams.ProtoReflect.Descriptor instead.
func (*BasicParams) Descriptor() ([]byte, []int) {
	return file_render_v1_render_proto_rawDescGZIP(), []int{1}
}

type Font struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Family  string  `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Style   string  `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	ScalePt float32 `protobuf:"fixed32,3,opt,name=scale_pt,json=scalePt,proto3" json:"scale_pt,omitempty"`
}

func (x *Font) Reset() {
	*x = Font{}
	if protoimpl.UnsafeEnabled {
		mi := &file_render_v1_render_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Font) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Font) ProtoMessage() {}

func (x *Font) ProtoReflect() protoreflect.Message {
	mi := &file_render_v1_render_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Font.ProtoReflect.Descriptor instead.
func (*Font) Descriptor() ([]byte, []int) {
	return file_render_v1_render_proto_rawDescGZIP(), []int{2}
}

func (x *Font) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *Font) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *Font) GetScalePt() float32 {
	if x != nil {
		return x.ScalePt
	}
	return 0
}

type WithTextParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShowArt       bool  `protobuf:"varint,1,opt,name=show_art,json=showArt,proto3" json:"show_art,omitempty"`
	ShowTrack     bool  `protobuf:"varint,2,opt,name=show_track,json=showTrack,proto3" json:"show_track,omitempty"`
	ShowAlbum     bool  `protobuf:"varint,3,opt,name=show_album,json=showAlbum,proto3" json:"show_album,omitempty"`
	ShowArtist    bool  `protobuf:"varint,4,opt,name=show_artist,json=showArtist,proto3" json:"show_artist,omitempty"`
	ShowPlayCount bool  `protobuf:"varint,5,opt,name=show_play_count,json=showPlayCount,proto3" json:"show_play_count,omitempty"`
	Font          *Font `protobuf:"bytes,6,opt,name=font,proto3" json:"font,omitempty"`
}

func (x *WithTextParams) Reset() {
	*x = WithTextParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_render_v1_render_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithTextParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithTextParams) ProtoMessage() {}

func (x *WithTextParams) ProtoReflect() protoreflect.Message {
	mi := &file_render_v1_render_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithTextParams.ProtoReflect.Descriptor instead.
func (*WithTextParams) Descriptor() ([]byte, []int) {
	return file_render_v1_render_proto_rawDescGZIP(), []int{3}
}

func (x *WithTextParams) GetShowArt() bool {
	if x != nil {
		return x.ShowArt
	}
	return false
}

func (x *WithTextParams) GetShowTrack() bool {
	if x != nil {
		return x.ShowTrack
	}
	return false
}

func (x *WithTextParams) GetShowAlbum() bool {
	if x != nil {
		return x.ShowAlbum
	}
	return false
}

func (x *WithTextParams) GetShowArtist() bool {
	if x != nil {
		return x.ShowArtist
	}
	return false
}

func (x *WithTextParams) GetShowPlayCount() bool {
	if x != nil {
		return x.ShowPlayCount
	}
	return false
}

func (x *WithTextParams) GetFont() *Font {
	if x != nil {
		return x.Font
	}
	return nil
}

type RenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileType v1.FileType `protobuf:"varint,1,opt,name=file_type,json=fileType,proto3,enum=shared.FileType" json:"file_type,omitempty"`
	Wall     []byte      `protobuf:"bytes,2,opt,name=wall,proto3" json:"wall,omitempty"`
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_render_v1_render_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_render_v1_render_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_render_v1_render_proto_rawDescGZIP(), []int{4}
}

func (x *RenderResponse) GetFileType() v1.FileType {
	if x != nil {
		return x.FileType
	}
	return v1.FileType(0)
}

func (x *RenderResponse) GetWall() []byte {
	if x != nil {
		return x.Wall
	}
	return nil
}

var File_render_v1_render_proto protoreflect.FileDescriptor

var file_render_v1_render_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x1a, 0x16, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x61, 0x79, 0x6f,
	0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xf9, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x2b, 0x0a, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x05, 0x62, 0x61, 0x73, 0x69, 0x63, 0x12, 0x35, 0x0a,
	0x09, 0x77, 0x69, 0x74, 0x68, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x54, 0x65,
	0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x48, 0x00, 0x52, 0x08, 0x77, 0x69, 0x74, 0x68,
	0x54, 0x65, 0x78, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x22, 0x0d, 0x0a, 0x0b,
	0x42, 0x61, 0x73, 0x69, 0x63, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x4f, 0x0a, 0x04, 0x46,
	0x6f, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x79, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x79, 0x6c,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x5f, 0x70, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x07, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x50, 0x74, 0x22, 0xd4, 0x01, 0x0a,
	0x0e, 0x57, 0x69, 0x74, 0x68, 0x54, 0x65, 0x78, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x68, 0x6f, 0x77, 0x41, 0x72, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68,
	0x6f, 0x77, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x73, 0x68, 0x6f, 0x77, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x6f,
	0x77, 0x5f, 0x61, 0x6c, 0x62, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73,
	0x68, 0x6f, 0x77, 0x41, 0x6c, 0x62, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x77,
	0x5f, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73,
	0x68, 0x6f, 0x77, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x68, 0x6f,
	0x77, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x73, 0x68, 0x6f, 0x77, 0x50, 0x6c, 0x61, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6f, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6e, 0x74, 0x52, 0x04, 0x66,
	0x6f, 0x6e, 0x74, 0x22, 0x53, 0x0a, 0x0e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x77, 0x61, 0x6c, 0x6c, 0x32, 0x48, 0x0a, 0x0d, 0x52, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x52, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x80, 0x01, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x42, 0x0b, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x67,
	0x68, 0x74, 0x6d, 0x61, 0x72, 0x6c, 0x69, 0x6e, 0x2f, 0x6d, 0x75, 0x72, 0x75, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2f, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x52, 0x58, 0x58, 0xaa, 0x02, 0x06, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0xca, 0x02,
	0x06, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72, 0xe2, 0x02, 0x12, 0x52, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x06, 0x52,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_render_v1_render_proto_rawDescOnce sync.Once
	file_render_v1_render_proto_rawDescData = file_render_v1_render_proto_rawDesc
)

func file_render_v1_render_proto_rawDescGZIP() []byte {
	file_render_v1_render_proto_rawDescOnce.Do(func() {
		file_render_v1_render_proto_rawDescData = protoimpl.X.CompressGZIP(file_render_v1_render_proto_rawDescData)
	})
	return file_render_v1_render_proto_rawDescData
}

var file_render_v1_render_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_render_v1_render_proto_goTypes = []interface{}{
	(*RenderRequest)(nil),  // 0: render.RenderRequest
	(*BasicParams)(nil),    // 1: render.BasicParams
	(*Font)(nil),           // 2: render.Font
	(*WithTextParams)(nil), // 3: render.WithTextParams
	(*RenderResponse)(nil), // 4: render.RenderResponse
	(v1.FileType)(0),       // 5: shared.FileType
	(*v11.Layout)(nil),     // 6: layout.Layout
	(*v1.Image)(nil),       // 7: shared.Image
}
var file_render_v1_render_proto_depIdxs = []int32{
	5, // 0: render.RenderRequest.file_type:type_name -> shared.FileType
	6, // 1: render.RenderRequest.layout:type_name -> layout.Layout
	7, // 2: render.RenderRequest.images:type_name -> shared.Image
	1, // 3: render.RenderRequest.basic:type_name -> render.BasicParams
	3, // 4: render.RenderRequest.with_text:type_name -> render.WithTextParams
	2, // 5: render.WithTextParams.font:type_name -> render.Font
	5, // 6: render.RenderResponse.file_type:type_name -> shared.FileType
	0, // 7: render.RenderService.Render:input_type -> render.RenderRequest
	4, // 8: render.RenderService.Render:output_type -> render.RenderResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_render_v1_render_proto_init() }
func file_render_v1_render_proto_init() {
	if File_render_v1_render_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_render_v1_render_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_render_v1_render_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasicParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_render_v1_render_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Font); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_render_v1_render_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithTextParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_render_v1_render_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_render_v1_render_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RenderRequest_Basic)(nil),
		(*RenderRequest_WithText)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_render_v1_render_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_render_v1_render_proto_goTypes,
		DependencyIndexes: file_render_v1_render_proto_depIdxs,
		MessageInfos:      file_render_v1_render_proto_msgTypes,
	}.Build()
	File_render_v1_render_proto = out.File
	file_render_v1_render_proto_rawDesc = nil
	file_render_v1_render_proto_goTypes = nil
	file_render_v1_render_proto_depIdxs = nil
}
